### ISSUE TITLE
Nieaktualny szablon Z-15

### ISSUE THREAD

**Issue by rafal-krypa** [steelman/Z-15#1]
Szablon z repozytorium na ostatniej stronie ma stopkę:
> Skład: Poligrafia ZUS/W-wa; zam. nr 2673/15

Szablon ze strony ZUS (http://www.zus.pl/default.asp?p=1&id=1083) aktualizowany 2.11.2016 r. ma zamiast tego:
> Skład: Poligrafia ZUS/W-wa; zam. nr 1986/16

**Comment by steelman** [comment]
Naprawione w 54bd5642
